import React from "react";
import path from "path";
import { renderToString } from "react-dom/server.node";
import { StaticRouter } from "react-router";
import { ChunkExtractor } from "@loadable/server";

// This is the stats file generated by webpack loadable plugin
const statsFile = path.resolve("dist/loadable-stats.json");
// We create an extractor from the statsFile
const extractor = new ChunkExtractor({ statsFile });
// Wrap your application using "collectChunks"

import { App } from "./App";

export default function ({ url, context }) {
  const jsx = extractor.collectChunks(
    <StaticRouter location={url} context={context}>
      <App />
    </StaticRouter>
  );

  return renderToString(jsx);
}
